### ISSUE TITLE
Add screen shots and how to use .md files.

### ISSUE THREAD

**Issue by iAhmadZain** [Ahmed-Adel-Ismail/Movies#1]
- Please add screens.
- Please add .md files to help people to use it.
- please add how to contribute.

;-)

**Comment by Ahmed-Adel-Ismail** [comment]
once I finish things from my side, will do so

**Comment by Ahmed-Adel-Ismail** [comment]
> * Please add screens.
> * Please add .md files to help people to use it.
> * please add how to contribute.
> 
> ;-)

done sir 👍
